### ISSUE TITLE
SLAMD Client Manager

### ISSUE THREAD

**Issue by ttrichard94** [dirmgr/slamd#1]
After running a build, the zip file, slamd-client-{DATE}.zip was created.  Within this file is a script called, "start-client-manager.sh".   There is a typo on Line 50:

-c "${SCRIPT_DIR}/start_client.sh" \

When the SLAMD server goes to start the requested clients, it displays an error that is cannot find "start_client.sh", because the filename has a "dash", not an "underscore", in the file name.

Updating the line to the following corrects the error:

-c "${SCRIPT_DIR}/start-client.sh" \

**Comment by dirmgr** [comment]
Thanks for pointing this out. I've just committed a fix for it.

**Comment by ttrichard94** [comment]
Thanks, and thanks for your work in updating SLAMD to function with current TLS1.2 protocols and ciphers.
