### ISSUE TITLE
SLAMD 2.1.0 with tomcat 6 does not support TLSv1.2

### ISSUE THREAD

**Issue by rrussell001** [dirmgr/slamd#2]
After enabling SSL in SLAMD Clients with JRE version 8 we are still not able to access directory services that are configured with TLSv1.1 or TLSv1.2.  SLAMD client connections are subsequently rejected.  This version of SLAMD only supports TLSv1.0 successfully.  Is there a version of SLAMD that supports TLSv1.2?

**Comment by dirmgr** [comment]
The SLAMD version 2.0.1 was released in 2010 and uses a very old version of the UnboundID LDAP SDK for some jobs and an absolutely ancient version (albeit still the latest one) Netscape Directory SDK for Java for others. I would expect that the UnboundID LDAP SDK could take advantage of at least TLSv1.2, but I could see problems with the Netscape SDK.

At any rate, I would recommend checking out and building from source so you get the latest version. I just tested it and it uses TLSv1.2 just fine when running on Java 8, and TLSv1.3 when running with Java 11. It uses much more modern versions of many of the libraries (including the UnboundID LDAP SDK) and offers significant improvements especially when it comes to the LDAP jobs.

**Comment by rrussell001** [comment]
Would you please send me a link to the latest version.  I am not a java
expert and would rather use a precompiled version of SLAMD that supports
TLSv1.2.

Regards,

Raymond

**Comment by dirmgr** [comment]
There currently aren't any builds available for download. The only way to get it at present would be to check out and build the code. However, it's pretty easy. Look at the "Building SLAMD" section on the main project page.

**Comment by rrussell001** [comment]
Neil,

Thanks for the response.  I am not a Java programmer and cannot do the work
myself.  So we are S.O.L when it comes to support for TLSv1.2 in SLAMD.
This tool will be obsolete soon.  I only hope jMeter will get their act
together...

Regards,

Raymond

**Comment by dirmgr** [comment]
The tool has been obsolete for over a decade, but thanks for your encouragement.

**Comment by rrussell001** [comment]
Obsolete for over a decade...  Now I know what to say to my customers and
Oracle support members.  Thanks..
